# https://taskfile.dev
version: '3'
vars:
  OUT_DIR: ../../../roms/demo.go-triangle
tasks:
  build:
    - mkdir -p {{.OUT_DIR}}
    - >
      tinygo build
      -target ../target.json
      -o {{.OUT_DIR}}/cart.wasm
      .
    - wasm-strip {{.OUT_DIR}}/cart.wasm
    - ls -lah {{.OUT_DIR}}
  default:
    - task: build
