# https://taskfile.dev
version: '3'

tasks:
  install-gofumpt:
    status:
      - which gofumpt
    cmds:
      # https://github.com/mvdan/gofumpt
      - go install mvdan.cc/gofumpt@latest
  install-golangci-lint:
    status:
      - which golangci-lint
    cmds:
      # https://golangci-lint.run/welcome/install/
      - >
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh
        | sh -s -- -b $(go env GOPATH)/bin v1.58.0

  release:
    cmds:
      - test {{.CLI_ARGS}}
      - git tag v{{.CLI_ARGS}}
      - git push
      - git push --tags
      - gh release create --generate-notes v{{.CLI_ARGS}}

  format:
    cmds:
      - task: install-gofumpt
      - gofumpt -w .
  lint:
    cmds:
      - task: install-golangci-lint
      - golangci-lint run
  test:
    cmds:
      - go test -count 1 ./...
  all:
    desc: run all code formatters, linters, and tests
    cmds:
      - task: format
      - task: lint
      - task: test
  default:
    cmds:
      - task: all
