# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  lint:
    cmds:
      - golangci-lint run
  test:
    cmds:
      - go test -count 1 ./...
  all:
    cmds:
      - task: lint
      - task: test
  default:
    cmds:
      - task: all
